// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Faction struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	People      []*Person `json:"people"`
	Places      []*Place  `json:"places"`
	Things      []*Thing  `json:"things"`
	Ideas       []*Idea   `json:"ideas"`
}

type Idea struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	People      []*Person  `json:"people"`
	Places      []*Place   `json:"places"`
	Things      []*Thing   `json:"things"`
	Factions    []*Faction `json:"factions"`
}

type NewPerson struct {
	Name        string `json:"name"`
	Description string `json:"description"`
}

type Person struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	People      []*Person  `json:"people"`
	Places      []*Place   `json:"places"`
	Things      []*Thing   `json:"things"`
	Ideas       []*Idea    `json:"ideas"`
	Factions    []*Faction `json:"factions"`
}

type Place struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Location    string     `json:"location"`
	People      []*Person  `json:"people"`
	Things      []*Thing   `json:"things"`
	Ideas       []*Idea    `json:"ideas"`
	Factions    []*Faction `json:"factions"`
}

type Thing struct {
	ID          string     `json:"id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	People      []*Person  `json:"people"`
	Places      []*Place   `json:"places"`
	Ideas       []*Idea    `json:"ideas"`
	Factions    []*Faction `json:"factions"`
}
